# Generated by Django 6.0.7 on 2026-08-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectimage_copy_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
