# Generated by Django 4.2.29 on 2026-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_approach_project_outcome_project_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Practical products backed by real logic.', max_length=200)),
                ('bio_paragraph_1', models.TextField()),
                ('bio_paragraph_2', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('linkedin_username', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default="Let's build something great.", max_length=200)),
                ('subheading', models.TextField(blank=True, help_text='The contact intro paragraph')),
                ('email', models.EmailField(max_length=254)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('linkedin_username', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentApproachStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='e.g. fa-clipboard-check, fa-hammer', max_length=100)),
            ],
            options={
                'verbose_name': 'Development Approach Step',
                'verbose_name_plural': 'Development Approach Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringFocusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_name', models.CharField(help_text='e.g. fa-layer-group, fa-database', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Engineering Focus Item',
                'verbose_name_plural': 'Engineering Focus Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_title', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(help_text='The main hero paragraph')),
                ('status_badge_text', models.CharField(default='Open to opportunities', max_length=100)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Hero Content',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_name', models.CharField(help_text='e.g. fa-django, fa-python', max_length=100)),
                ('brand_color', models.CharField(blank=True, help_text='Hex color e.g. #092E20', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatIBuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_name', models.CharField(help_text='e.g. fa-layer-group, fa-server', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'What I Build Item',
                'verbose_name_plural': 'What I Build Items',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.technology'),
        ),
    ]
