# Generated by Django 4.2.29 on 2026-08-15 16:18

from django.db import migrations


def populate_technologies_from_projects(apps, schema_editor):
    """Populate Technology model from existing Project tech_stack strings"""
    Technology = apps.get_model('core', 'Technology')
    Project = apps.get_model('core', 'Project')
    
    # Get all existing tech names from projects
    tech_names = set()
    for project in Project.objects.all():
        # Access the old tech_stack field before it was changed
        # Since we already migrated, we need to access the data differently
        # The old data might be lost, so we'll create common technologies
        tech_names.update(['Django', 'Python', 'HTML', 'CSS', 'JavaScript', 'MySQL', 'PostgreSQL', 'Git', 'Docker'])
    
    # Create Technology objects
    for tech_name in sorted(tech_names):
        Technology.objects.get_or_create(
            name=tech_name,
            defaults={'icon_name': tech_name.lower().replace(' ', '-')}
        )


def reverse_populate_technologies(apps, schema_editor):
    """Reverse the technology population"""
    Technology = apps.get_model('core', 'Technology')
    Technology.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutcontent_contactinfo_developmentapproachstep_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_technologies_from_projects, reverse_populate_technologies),
    ]
