# Generated by Django 4.2.29 on 2026-08-15 16:29

from django.db import migrations


def populate_initial_content(apps, schema_editor):
    """Populate all new models with content from templates"""
    HeroContent = apps.get_model('core', 'HeroContent')
    AboutContent = apps.get_model('core', 'AboutContent')
    ContactInfo = apps.get_model('core', 'ContactInfo')
    WhatIBuildItem = apps.get_model('core', 'WhatIBuildItem')
    EngineeringFocusItem = apps.get_model('core', 'EngineeringFocusItem')
    DevelopmentApproachStep = apps.get_model('core', 'DevelopmentApproachStep')
    Profile = apps.get_model('core', 'Profile')
    Project = apps.get_model('core', 'Project')
    
    # Get existing profile data
    profile = Profile.objects.first()
    
    # Create HeroContent from existing profile data
    if profile and not HeroContent.objects.exists():
        HeroContent.objects.create(
            name=profile.name,
            role_title=profile.role,
            tagline=profile.tagline,
            description=profile.about,
            status_badge_text="Open to opportunities"
        )
    
    # Create AboutContent
    if not AboutContent.objects.exists():
        AboutContent.objects.create(
            heading="Practical products backed by real logic.",
            bio_paragraph_1=profile.about if profile else "I build practical, dependable web applications with Python, Django and modern frontend technologies.",
            bio_paragraph_2="",
            location=profile.location if profile else "Salem",
            email=profile.email if profile else "kaviyarasank317@gmail.com",
            github_username=profile.github.split('/')[-1] if profile and profile.github else "Kaviyarasan-trader",
            linkedin_username=profile.linkedin.split('/')[-1] if profile and profile.linkedin else "kaviyarasan-r-b79380385"
        )
    
    # Create ContactInfo
    if not ContactInfo.objects.exists():
        ContactInfo.objects.create(
            heading="Let's build something great.",
            subheading="Have a role, project or idea in mind? Let's discuss how we can build something meaningful together.",
            email=profile.email if profile else "kaviyarasank317@gmail.com",
            github_username=profile.github.split('/')[-1] if profile and profile.github else "Kaviyarasan-trader",
            linkedin_username=profile.linkedin.split('/')[-1] if profile and profile.linkedin else "kaviyarasan-r-b79380385"
        )
    
    # Create WhatIBuildItem items (from about-hl section)
    if not WhatIBuildItem.objects.exists():
        WhatIBuildItem.objects.create(
            order=1,
            icon_name="fa-layer-group",
            title="Full-stack development",
            description="End-to-end features, from database schema to a polished interface."
        )
        WhatIBuildItem.objects.create(
            order=2,
            icon_name="fa-server",
            title="Backend engineering",
            description="Django models, views, authentication and API workflows."
        )
        WhatIBuildItem.objects.create(
            order=3,
            icon_name="fa-database",
            title="Database-driven apps",
            description="Structured data with SQL, ORM queries and relational design."
        )
        WhatIBuildItem.objects.create(
            order=4,
            icon_name="fa-mobile-screen-button",
            title="Responsive web UI",
            description="Interfaces that adapt cleanly across desktop and mobile."
        )
    
    # Create EngineeringFocusItem items (from focus-list section)
    if not EngineeringFocusItem.objects.exists():
        EngineeringFocusItem.objects.create(
            order=1,
            icon_name="fa-layer-group",
            title="Full-stack web applications",
            description="Complete applications built with Django, Python and modern frontend technologies — from database schema to interface."
        )
        EngineeringFocusItem.objects.create(
            order=2,
            icon_name="fa-database",
            title="Database-driven systems",
            description="Applications organised around structured relational data — models, queries, relationships and data integrity."
        )
        EngineeringFocusItem.objects.create(
            order=3,
            icon_name="fa-server",
            title="Backend development",
            description="Django business logic, authentication, CRUD workflows and API integration that keep features reliable."
        )
        EngineeringFocusItem.objects.create(
            order=4,
            icon_name="fa-mobile-screen-button",
            title="Responsive user experiences",
            description="Practical interfaces designed to work well across desktop and mobile, with clean interaction states."
        )
    
    # Create DevelopmentApproachStep items (from approach-steps section)
    if not DevelopmentApproachStep.objects.exists():
        DevelopmentApproachStep.objects.create(
            order=1,
            step_number=1,
            title="Plan",
            description="Clarify the requirements and map the user flow before writing code.",
            icon_name="fa-clipboard-check"
        )
        DevelopmentApproachStep.objects.create(
            order=2,
            step_number=2,
            title="Build",
            description="Design the backend logic and the frontend interaction that bring the feature to life.",
            icon_name="fa-hammer"
        )
        DevelopmentApproachStep.objects.create(
            order=3,
            step_number=3,
            title="Integrate",
            description="Connect databases, APIs and application workflows into one coherent system.",
            icon_name="fa-plug"
        )
        DevelopmentApproachStep.objects.create(
            order=4,
            step_number=4,
            title="Refine",
            description="Test, debug and polish usability until it feels dependable across devices.",
            icon_name="fa-wand-magic-sparkles"
        )
    
    # Update project order values
    projects = Project.objects.all()
    for idx, project in enumerate(projects, start=1):
        project.order = idx
        project.save()


def reverse_populate_initial_content(apps, schema_editor):
    """Reverse the initial content population"""
    HeroContent = apps.get_model('core', 'HeroContent')
    AboutContent = apps.get_model('core', 'AboutContent')
    ContactInfo = apps.get_model('core', 'ContactInfo')
    WhatIBuildItem = apps.get_model('core', 'WhatIBuildItem')
    EngineeringFocusItem = apps.get_model('core', 'EngineeringFocusItem')
    DevelopmentApproachStep = apps.get_model('core', 'DevelopmentApproachStep')
    
    HeroContent.objects.all().delete()
    AboutContent.objects.all().delete()
    ContactInfo.objects.all().delete()
    WhatIBuildItem.objects.all().delete()
    EngineeringFocusItem.objects.all().delete()
    DevelopmentApproachStep.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20260815_2148'),
    ]

    operations = [
        migrations.RunPython(populate_initial_content, reverse_populate_initial_content),
    ]
